DECLARE
  V_COUNT INTEGER;
  V_SEQUENCE VARCHAR(40);
  V_CURSOR_NAME INTEGER;
  V_RET INTEGER;
BEGIN
  V_SEQUENCE := 'users_PK_SEQUENCE';
  SELECT COUNT(1) INTO V_COUNT FROM USER_SEQUENCES WHERE SEQUENCE_NAME = V_SEQUENCE;
  IF V_COUNT = 1 THEN
    V_CURSOR_NAME := DBMS_SQL.OPEN_CURSOR;
    DBMS_SQL.PARSE(V_CURSOR_NAME, 'DROP SEQUENCE "' || V_SEQUENCE ||'"', DBMS_SQL.NATIVE);
    V_RET := DBMS_SQL.EXECUTE(V_CURSOR_NAME);
  END IF;
END;
