DECLARE
  V_COUNT INTEGER;
  V_SQL VARCHAR(2000);
  V_TABLE VARCHAR(40);
  V_CURSOR_NAME INTEGER;
  V_RET INTEGER;
BEGIN
  V_TABLE := 'HOSTS';
  V_SQL := '
      CREATE TABLE HOSTS (
      HOST_ID NUMBER (11)  NOT NULL,
      NAME    VARCHAR2 (100)  NOT NULL
    )
  ';
  SELECT COUNT(1) INTO V_COUNT FROM USER_TABLES WHERE TABLE_NAME = V_TABLE;
  IF V_COUNT = 0 THEN
    V_CURSOR_NAME := DBMS_SQL.OPEN_CURSOR;
    DBMS_SQL.PARSE(V_CURSOR_NAME, V_SQL, DBMS_SQL.NATIVE);
    V_RET := DBMS_SQL.EXECUTE(V_CURSOR_NAME);
  END IF;
END;
