DECLARE
  V_COUNT INTEGER;
  V_USER VARCHAR2(100);
  V_PASSWORD VARCHAR2(100);
  V_CURSOR_NAME INTEGER;
  V_RET INTEGER;
BEGIN
  V_USER := 'USERNAME';
  V_PASSWORD := 'PASS';
  SELECT COUNT(1) INTO V_COUNT FROM ALL_USERS WHERE USERNAME = V_USER;
  IF V_COUNT = 0 THEN
    V_CURSOR_NAME := DBMS_SQL.OPEN_CURSOR;
    DBMS_SQL.PARSE(V_CURSOR_NAME, 'CREATE USER ' || V_USER || ' IDENTIFIED BY ' || V_PASSWORD, DBMS_SQL.NATIVE);
    V_RET := DBMS_SQL.EXECUTE(V_CURSOR_NAME);
  END IF;
END;
